[project]
name = "data-engineer-challenge-master"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "awscli-local>=0.22.2",
    "boto3>=1.40.22",
    "terraform-local>=0.24.1",
]
